---
title: "Plotly Types"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Examples of plotly. 

We're gonna look at the NYC Airbnb data. 

```{r}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(httr)
library(jsonlite)
library(dplyr)
```

## Extracting NYC restaurant data
```{r}
get_all_inspections = function(url) {
  
  all_inspections = vector("list", length = 0)
  
  loop_index = 1
  chunk_size = 50000
  DO_NEXT = TRUE
  
  while (DO_NEXT) {
    message("Getting data, page ", loop_index)
    
    all_inspections[[loop_index]] = 
      GET(url,
          query = list(`$order` = "zipcode",
                       `$limit` = chunk_size,
                       `$offset` = as.integer((loop_index - 1) * chunk_size)
                       )
          ) %>%
      content("text") %>%
      fromJSON() %>%
      as_tibble()
    
    DO_NEXT = dim(all_inspections[[loop_index]])[1] == chunk_size
    loop_index = loop_index + 1
  }
  
  all_inspections
  
}

url = "https://data.cityofnewyork.us/resource/43nn-pn8j.json"

nyc_inspections = 
  get_all_inspections(url) %>%
  bind_rows() 
```

# Plots 

## Boxplot (kinda fail lol)
```{r}
nyc_inspections |>
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating))
nyc_airbnb |>
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) |> 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~price, text = ~text_label, alpha = 0.5)
```

## Bar Graph
```{r}
nyc_inspections <- nyc_inspections %>%
  filter(!is.na(boro), !is.na(cuisine_description)) %>%  
  mutate(boro = str_to_title(boro),                    
         cuisine_description = str_to_title(cuisine_description))

plot_ly(data = rest_inspec %>%
           group_by(boro, cuisine_description) %>%
           summarise(count = n()) %>%
           arrange(boro, desc(count)) %>%
           group_by(boro) %>%
           slice_head(n = 10) %>%
           ungroup() %>%
           mutate(cuisine_description = fct_reorder(cuisine_description, count)),
         x = ~cuisine_description, y = ~count, color = ~boro, 
         type = "bar", colors = "viridis") %>%
  layout(title = "Top 10 Cuisine Types by Borough in NYC Restaurant Inspections",
         xaxis = list(title = "Cuisine Type"), 
         yaxis = list(title = "Number of Restaurants"),
         barmode = "group", 
         showlegend = TRUE)
```

## bar plot 
```{r}
nyc_airbnb |> 
  count(neighbourhood) |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) |> 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", colors = "viridis")
```

## ggplotly 
```{r}
scatter_ggplot = 
  nyc_airbnb |>
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point(alpha = 0.25) +
  coord_cartesian()

ggplotly(scatter_ggplot)
```


